export { SliceRenderer } from './renderer/slice-renderer'
export { CanvasRenderer } from './renderer/canvas-renderer'
export { sliceMesh, computeBoundingBox } from './core/slicer'
export { buildLocalBasis, projectPointTo2D, toCanvasCoord, projectSegments } from './core/projection'
export { createSlicer, createBatchSlicer } from './core/create-slicer'
export { GPUSlicer } from './core/gpu-slicer'
export { CPUSlicer } from './core/cpu-slicer'
export { BatchGPUSlicer } from './core/batch-gpu-slicer'
export { planChunks } from './core/chunk-planner'
export { getGPUDevice, isWebGPUAvailable } from './core/gpu-device'
export type { MeshSlicer } from './core/slicer-interface'
export type { BatchMeshSlicer } from './core/batch-slicer-interface'
export * from './core/vec3'
export * from './types'
